apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80             # Port on which the service will be exposed internally
      targetPort: 80     # Port on which the container is listening
      nodePort: 30000      # Port on which the service will be accessible externally


