name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Create .kube directory
        run: |
          mkdir -p $HOME/.kube

      - name: Decode KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Verify KUBECONFIG File
        run: |
          cat $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f wisecow-app/wisecow-deployment.yaml
          kubectl apply -f wisecow-app/wisecow-service.yaml
      
