name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Install kubectl
        uses: azure/setup-kubectl@v2
        with:
          version: 'v1.24.0'  # Specify the kubectl version you need

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f wisecow-app/wisecow-deployment.yaml
          kubectl apply -f wisecow-app/wisecow-service.yaml
